_CITY_TO_MSA: dict[tuple[str, str], str] = {
    # California
    ("anaheim",          "CA"): "Anaheim-Santa Ana-Irvine",
    ("santa ana",        "CA"): "Anaheim-Santa Ana-Irvine",
    ("irvine",           "CA"): "Anaheim-Santa Ana-Irvine",
    ("los angeles",      "CA"): "L.A. - Long Beach-Glendale",
    ("long beach",       "CA"): "L.A. - Long Beach-Glendale",
    ("glendale",         "CA"): "L.A. - Long Beach-Glendale",
    ("burbank",          "CA"): "L.A. - Long Beach-Glendale",
    ("pasadena",         "CA"): "L.A. - Long Beach-Glendale",
    ("torrance",         "CA"): "L.A. - Long Beach-Glendale",
    ("inglewood",        "CA"): "L.A. - Long Beach-Glendale",
    ("compton",          "CA"): "L.A. - Long Beach-Glendale",
    ("san francisco",    "CA"): "San Francisco",
    ("san jose",         "CA"): "San Jose-Sunnyvale-S. Clara",
    ("sunnyvale",        "CA"): "San Jose-Sunnyvale-S. Clara",
    ("santa clara",      "CA"): "San Jose-Sunnyvale-S. Clara",
    ("cupertino",        "CA"): "San Jose-Sunnyvale-S. Clara",
    ("mountain view",    "CA"): "San Jose-Sunnyvale-S. Clara",
    ("palo alto",        "CA"): "San Jose-Sunnyvale-S. Clara",
    ("oakland",          "CA"): "Oakland-Hayward-Berkeley",
    ("hayward",          "CA"): "Oakland-Hayward-Berkeley",
    ("berkeley",         "CA"): "Oakland-Hayward-Berkeley",
    ("fremont",          "CA"): "Oakland-Hayward-Berkeley",
    ("san diego",        "CA"): "San Diego",
    ("chula vista",      "CA"): "San Diego",
    ("riverside",        "CA"): "Riverside-San Bernardino",
    ("san bernardino",   "CA"): "Riverside-San Bernardino",
    ("ontario",          "CA"): "Riverside-San Bernardino",
    ("moreno valley",    "CA"): "Riverside-San Bernardino",
    ("oxnard",           "CA"): "Oxnard-Thousand Oaks",
    ("thousand oaks",    "CA"): "Oxnard-Thousand Oaks",
    ("ventura",          "CA"): "Oxnard-Thousand Oaks",
    ("santa barbara",    "CA"): "Santa Maria-Santa Barbara",
    ("santa maria",      "CA"): "Santa Maria-Santa Barbara",
    ("santa rosa",       "CA"): "Santa Rosa",
    ("vallejo",          "CA"): "Vallejo/Fairfield/Napa",
    ("fairfield",        "CA"): "Vallejo/Fairfield/Napa",
    ("napa",             "CA"): "Vallejo/Fairfield/Napa",
    # Texas
    ("dallas",           "TX"): "Dallas-Plano-Irving",
    ("plano",            "TX"): "Dallas-Plano-Irving",
    ("irving",           "TX"): "Dallas-Plano-Irving",
    ("garland",          "TX"): "Dallas-Plano-Irving",
    ("mesquite",         "TX"): "Dallas-Plano-Irving",
    ("richardson",       "TX"): "Dallas-Plano-Irving",
    ("fort worth",       "TX"): "Ft. Worth-Arlington",
    ("arlington",        "TX"): "Ft. Worth-Arlington",
    ("houston",          "TX"): "Houston",
    ("austin",           "TX"): "Austin",
    ("san antonio",      "TX"): "San Antonio",
    # Florida
    ("miami",            "FL"): "Miami-Kendall",
    ("kendall",          "FL"): "Miami-Kendall",
    ("hialeah",          "FL"): "Miami-Kendall",
    ("doral",            "FL"): "Miami-Kendall",
    ("fort lauderdale",  "FL"): "Ft. Lauderdale-Pompano",
    ("pompano beach",    "FL"): "Ft. Lauderdale-Pompano",
    ("hollywood",        "FL"): "Ft. Lauderdale-Pompano",
    ("coral springs",    "FL"): "Ft. Lauderdale-Pompano",
    ("west palm beach",  "FL"): "West Palm-Boca-Delray",
    ("boca raton",       "FL"): "West Palm-Boca-Delray",
    ("delray beach",     "FL"): "West Palm-Boca-Delray",
    ("boynton beach",    "FL"): "West Palm-Boca-Delray",
    ("orlando",          "FL"): "Orlando",
    ("kissimmee",        "FL"): "Orlando",
    ("sanford",          "FL"): "Orlando",
    ("jacksonville",     "FL"): "Jacksonville",
    ("tampa",            "FL"): "Tampa-St. Pete",
    ("st. pete",         "FL"): "Tampa-St. Pete",
    ("st. petersburg",   "FL"): "Tampa-St. Pete",
    ("clearwater",       "FL"): "Tampa-St. Pete",
    ("palm bay",         "FL"): "Palm Bay-Melbourne",
    ("melbourne",        "FL"): "Palm Bay-Melbourne",
    ("naples",           "FL"): "Naples-Marco Island",
    ("marco island",     "FL"): "Naples-Marco Island",
    ("sarasota",         "FL"): "N. Port-Sarasota-Bradenton",
    ("bradenton",        "FL"): "N. Port-Sarasota-Bradenton",
    ("north port",       "FL"): "N. Port-Sarasota-Bradenton",
    # Georgia
    ("atlanta",          "GA"): "Atlanta",
    ("marietta",         "GA"): "Atlanta",
    ("savannah",         "GA"): "Atlanta",
    # Illinois
    ("chicago",          "IL"): "Chicago",
    ("aurora",           "IL"): "Chicago",
    ("naperville",       "IL"): "Chicago",
    # Colorado
    ("denver",           "CO"): "Denver",
    ("aurora",           "CO"): "Denver",
    ("lakewood",         "CO"): "Denver",
    ("boulder",          "CO"): "Boulder",
    # Arizona
    ("phoenix",          "AZ"): "Phoenix",
    ("scottsdale",       "AZ"): "Phoenix",
    ("tempe",            "AZ"): "Phoenix",
    ("mesa",             "AZ"): "Phoenix",
    ("chandler",         "AZ"): "Phoenix",
    ("gilbert",          "AZ"): "Phoenix",
    ("glendale",         "AZ"): "Phoenix",
    ("peoria",           "AZ"): "Phoenix",
    # Nevada
    ("las vegas",        "NV"): "Las Vegas",
    ("henderson",        "NV"): "Las Vegas",
    ("north las vegas",  "NV"): "Las Vegas",
    # Washington
    ("seattle",          "WA"): "Seattle",
    ("bellevue",         "WA"): "Seattle",
    ("redmond",          "WA"): "Seattle",
    ("tacoma",           "WA"): "Tacoma-Lakewood",
    ("lakewood",         "WA"): "Tacoma-Lakewood",
    # Oregon
    ("portland",         "OR"): "Portland",
    ("beaverton",        "OR"): "Portland",
    ("lake oswego",      "OR"): "Portland",
    ("gresham",          "OR"): "Portland",
    ("hillsboro",        "OR"): "Portland",
    ("tualatin",         "OR"): "Portland",
    ("tigard",           "OR"): "Portland",
    ("milwaukie",        "OR"): "Portland",
    ("happy valley",     "OR"): "Portland",
    ("west linn",        "OR"): "Portland",
    ("oregon city",      "OR"): "Portland",
    ("wilsonville",      "OR"): "Portland",
    # Utah
    ("salt lake city",   "UT"): "Salt Lake City",
    ("west valley city", "UT"): "Salt Lake City",
    ("provo",            "UT"): "Salt Lake City",
    # North Carolina
    ("charlotte",        "NC"): "Charlotte",
    ("raleigh",          "NC"): "Raleigh",
    ("durham",           "NC"): "Raleigh",
    ("cary",             "NC"): "Raleigh",
    # Tennessee
    ("nashville",        "TN"): "Nashville",
    ("memphis",          "TN"): "Nashville",
    # South Carolina
    ("charleston",       "SC"): "Charleston",
    ("greenville",       "SC"): "Greenville",
    # Virginia / DC area
    ("arlington",        "VA"): "Washington-Northern VA",
    ("alexandria",       "VA"): "Washington-Northern VA",
    ("falls church",     "VA"): "Washington-Northern VA",
    ("fairfax",          "VA"): "Washington-Northern VA",
    ("reston",           "VA"): "Washington-Northern VA",
    ("washington",       "DC"): "Washington-Northern VA",
    # Maryland
    ("baltimore",        "MD"): "Baltimore",
    # New York
    ("new york",         "NY"): "New York-White Plains",
    ("white plains",     "NY"): "New York-White Plains",
    ("yonkers",          "NY"): "New York-White Plains",
    ("bronx",            "NY"): "New York-White Plains",
    ("brooklyn",         "NY"): "New York-White Plains",
    ("queens",           "NY"): "New York-White Plains",
    ("staten island",    "NY"): "New York-White Plains",
    ("hempstead",        "NY"): "Nassau Co. - Suffolk Co.",
    ("brentwood",        "NY"): "Nassau Co. - Suffolk Co.",
    # New Jersey
    ("newark",           "NJ"): "Newark-Jersey City",
    ("jersey city",      "NJ"): "Newark-Jersey City",
    ("paterson",         "NJ"): "Newark-Jersey City",
    # Connecticut
    ("bridgeport",       "CT"): "Bridgeport-Stamford",
    ("stamford",         "CT"): "Bridgeport-Stamford",
    ("norwalk",          "CT"): "Bridgeport-Stamford",
    # Massachusetts
    ("boston",           "MA"): "Boston",
    ("worcester",        "MA"): "Worcester",
    ("springfield",      "MA"): "Boston",
    # Pennsylvania
    ("philadelphia",     "PA"): "Philadelphia",
    # Minnesota
    ("minneapolis",      "MN"): "Minneapolis-St. Paul",
    ("st. paul",         "MN"): "Minneapolis-St. Paul",
    ("saint paul",       "MN"): "Minneapolis-St. Paul",
    ("bloomington",      "MN"): "Minneapolis-St. Paul",
}


def msa_for_deal(deal: dict) -> str:
    """Return the MSA label for a deal dict, falling back to raw city name."""
    cs = deal.get("city_state", "")
    parts = cs.split(",")
    city  = parts[0].strip().lower()
    state = parts[1].strip().upper() if len(parts) > 1 else ""
    return _CITY_TO_MSA.get((city, state)) or cs.split(",")[0].strip().title() or "Other"
