_CITY_TO_MSA: dict[tuple[str, str], str] = {
    # ── California ──────────────────────────────────────────────────────────────
    # Orange County
    ("anaheim",              "CA"): "Anaheim-Santa Ana-Irvine",
    ("santa ana",            "CA"): "Anaheim-Santa Ana-Irvine",
    ("irvine",               "CA"): "Anaheim-Santa Ana-Irvine",
    ("orange",               "CA"): "Anaheim-Santa Ana-Irvine",
    ("garden grove",         "CA"): "Anaheim-Santa Ana-Irvine",
    ("huntington beach",     "CA"): "Anaheim-Santa Ana-Irvine",
    ("fullerton",            "CA"): "Anaheim-Santa Ana-Irvine",
    ("costa mesa",           "CA"): "Anaheim-Santa Ana-Irvine",
    ("mission viejo",        "CA"): "Anaheim-Santa Ana-Irvine",
    ("lake forest",          "CA"): "Anaheim-Santa Ana-Irvine",
    ("buena park",           "CA"): "Anaheim-Santa Ana-Irvine",
    ("newport beach",        "CA"): "Anaheim-Santa Ana-Irvine",
    ("laguna niguel",        "CA"): "Anaheim-Santa Ana-Irvine",
    ("aliso viejo",          "CA"): "Anaheim-Santa Ana-Irvine",
    ("tustin",               "CA"): "Anaheim-Santa Ana-Irvine",
    ("yorba linda",          "CA"): "Anaheim-Santa Ana-Irvine",
    ("placentia",            "CA"): "Anaheim-Santa Ana-Irvine",
    ("brea",                 "CA"): "Anaheim-Santa Ana-Irvine",
    ("laguna hills",         "CA"): "Anaheim-Santa Ana-Irvine",
    ("san clemente",         "CA"): "Anaheim-Santa Ana-Irvine",
    ("dana point",           "CA"): "Anaheim-Santa Ana-Irvine",
    # Los Angeles
    ("los angeles",          "CA"): "L.A. - Long Beach-Glendale",
    ("long beach",           "CA"): "L.A. - Long Beach-Glendale",
    ("glendale",             "CA"): "L.A. - Long Beach-Glendale",
    ("burbank",              "CA"): "L.A. - Long Beach-Glendale",
    ("pasadena",             "CA"): "L.A. - Long Beach-Glendale",
    ("torrance",             "CA"): "L.A. - Long Beach-Glendale",
    ("inglewood",            "CA"): "L.A. - Long Beach-Glendale",
    ("compton",              "CA"): "L.A. - Long Beach-Glendale",
    ("hawthorne",            "CA"): "L.A. - Long Beach-Glendale",
    ("el monte",             "CA"): "L.A. - Long Beach-Glendale",
    ("downey",               "CA"): "L.A. - Long Beach-Glendale",
    ("west covina",          "CA"): "L.A. - Long Beach-Glendale",
    ("pomona",               "CA"): "L.A. - Long Beach-Glendale",
    ("santa monica",         "CA"): "L.A. - Long Beach-Glendale",
    ("culver city",          "CA"): "L.A. - Long Beach-Glendale",
    ("beverly hills",        "CA"): "L.A. - Long Beach-Glendale",
    ("west hollywood",       "CA"): "L.A. - Long Beach-Glendale",
    ("el segundo",           "CA"): "L.A. - Long Beach-Glendale",
    ("manhattan beach",      "CA"): "L.A. - Long Beach-Glendale",
    ("redondo beach",        "CA"): "L.A. - Long Beach-Glendale",
    ("hermosa beach",        "CA"): "L.A. - Long Beach-Glendale",
    ("gardena",              "CA"): "L.A. - Long Beach-Glendale",
    ("carson",               "CA"): "L.A. - Long Beach-Glendale",
    ("lakewood",             "CA"): "L.A. - Long Beach-Glendale",
    ("norwalk",              "CA"): "L.A. - Long Beach-Glendale",
    ("whittier",             "CA"): "L.A. - Long Beach-Glendale",
    ("alhambra",             "CA"): "L.A. - Long Beach-Glendale",
    ("arcadia",              "CA"): "L.A. - Long Beach-Glendale",
    ("monrovia",             "CA"): "L.A. - Long Beach-Glendale",
    ("covina",               "CA"): "L.A. - Long Beach-Glendale",
    ("glendora",             "CA"): "L.A. - Long Beach-Glendale",
    ("azusa",                "CA"): "L.A. - Long Beach-Glendale",
    ("duarte",               "CA"): "L.A. - Long Beach-Glendale",
    ("la puente",            "CA"): "L.A. - Long Beach-Glendale",
    ("la habra",             "CA"): "L.A. - Long Beach-Glendale",
    ("diamond bar",          "CA"): "L.A. - Long Beach-Glendale",
    ("walnut",               "CA"): "L.A. - Long Beach-Glendale",
    ("industry",             "CA"): "L.A. - Long Beach-Glendale",
    ("signal hill",          "CA"): "L.A. - Long Beach-Glendale",
    ("paramount",            "CA"): "L.A. - Long Beach-Glendale",
    ("bell gardens",         "CA"): "L.A. - Long Beach-Glendale",
    ("south gate",           "CA"): "L.A. - Long Beach-Glendale",
    ("lynwood",              "CA"): "L.A. - Long Beach-Glendale",
    ("maywood",              "CA"): "L.A. - Long Beach-Glendale",
    ("huntington park",      "CA"): "L.A. - Long Beach-Glendale",
    ("montebello",           "CA"): "L.A. - Long Beach-Glendale",
    ("pico rivera",          "CA"): "L.A. - Long Beach-Glendale",
    ("san gabriel",          "CA"): "L.A. - Long Beach-Glendale",
    ("temple city",          "CA"): "L.A. - Long Beach-Glendale",
    ("rosemead",             "CA"): "L.A. - Long Beach-Glendale",
    ("la canada flintridge", "CA"): "L.A. - Long Beach-Glendale",
    ("la crescenta",         "CA"): "L.A. - Long Beach-Glendale",
    ("chatsworth",           "CA"): "L.A. - Long Beach-Glendale",
    ("northridge",           "CA"): "L.A. - Long Beach-Glendale",
    ("reseda",               "CA"): "L.A. - Long Beach-Glendale",
    ("van nuys",             "CA"): "L.A. - Long Beach-Glendale",
    ("canoga park",          "CA"): "L.A. - Long Beach-Glendale",
    ("woodland hills",       "CA"): "L.A. - Long Beach-Glendale",
    ("tarzana",              "CA"): "L.A. - Long Beach-Glendale",
    ("encino",               "CA"): "L.A. - Long Beach-Glendale",
    ("sherman oaks",         "CA"): "L.A. - Long Beach-Glendale",
    ("studio city",          "CA"): "L.A. - Long Beach-Glendale",
    ("north hollywood",      "CA"): "L.A. - Long Beach-Glendale",
    ("sun valley",           "CA"): "L.A. - Long Beach-Glendale",
    ("pacoima",              "CA"): "L.A. - Long Beach-Glendale",
    ("sylmar",               "CA"): "L.A. - Long Beach-Glendale",
    ("granada hills",        "CA"): "L.A. - Long Beach-Glendale",
    ("porter ranch",         "CA"): "L.A. - Long Beach-Glendale",
    ("santa clarita",        "CA"): "L.A. - Long Beach-Glendale",
    ("valencia",             "CA"): "L.A. - Long Beach-Glendale",
    ("palmdale",             "CA"): "L.A. - Long Beach-Glendale",
    ("lancaster",            "CA"): "L.A. - Long Beach-Glendale",
    # San Francisco Bay Area
    ("san francisco",        "CA"): "San Francisco",
    ("daly city",            "CA"): "San Francisco",
    ("south san francisco",  "CA"): "San Francisco",
    ("san mateo",            "CA"): "San Francisco",
    ("foster city",          "CA"): "San Francisco",
    ("burlingame",           "CA"): "San Francisco",
    ("millbrae",             "CA"): "San Francisco",
    ("redwood city",         "CA"): "San Francisco",
    ("san carlos",           "CA"): "San Francisco",
    ("belmont",              "CA"): "San Francisco",
    ("menlo park",           "CA"): "San Francisco",
    ("atherton",             "CA"): "San Francisco",
    ("pacifica",             "CA"): "San Francisco",
    # San Jose
    ("san jose",             "CA"): "San Jose-Sunnyvale-S. Clara",
    ("sunnyvale",            "CA"): "San Jose-Sunnyvale-S. Clara",
    ("santa clara",          "CA"): "San Jose-Sunnyvale-S. Clara",
    ("cupertino",            "CA"): "San Jose-Sunnyvale-S. Clara",
    ("mountain view",        "CA"): "San Jose-Sunnyvale-S. Clara",
    ("palo alto",            "CA"): "San Jose-Sunnyvale-S. Clara",
    ("los altos",            "CA"): "San Jose-Sunnyvale-S. Clara",
    ("los gatos",            "CA"): "San Jose-Sunnyvale-S. Clara",
    ("campbell",             "CA"): "San Jose-Sunnyvale-S. Clara",
    ("milpitas",             "CA"): "San Jose-Sunnyvale-S. Clara",
    ("saratoga",             "CA"): "San Jose-Sunnyvale-S. Clara",
    ("gilroy",               "CA"): "San Jose-Sunnyvale-S. Clara",
    ("morgan hill",          "CA"): "San Jose-Sunnyvale-S. Clara",
    # Oakland / East Bay
    ("oakland",              "CA"): "Oakland-Hayward-Berkeley",
    ("hayward",              "CA"): "Oakland-Hayward-Berkeley",
    ("berkeley",             "CA"): "Oakland-Hayward-Berkeley",
    ("fremont",              "CA"): "Oakland-Hayward-Berkeley",
    ("richmond",             "CA"): "Oakland-Hayward-Berkeley",
    ("san leandro",          "CA"): "Oakland-Hayward-Berkeley",
    ("alameda",              "CA"): "Oakland-Hayward-Berkeley",
    ("emeryville",           "CA"): "Oakland-Hayward-Berkeley",
    ("piedmont",             "CA"): "Oakland-Hayward-Berkeley",
    ("union city",           "CA"): "Oakland-Hayward-Berkeley",
    ("newark",               "CA"): "Oakland-Hayward-Berkeley",
    ("pleasanton",           "CA"): "Oakland-Hayward-Berkeley",
    ("livermore",            "CA"): "Oakland-Hayward-Berkeley",
    ("dublin",               "CA"): "Oakland-Hayward-Berkeley",
    ("san ramon",            "CA"): "Oakland-Hayward-Berkeley",
    ("walnut creek",         "CA"): "Oakland-Hayward-Berkeley",
    ("concord",              "CA"): "Oakland-Hayward-Berkeley",
    ("antioch",              "CA"): "Oakland-Hayward-Berkeley",
    ("pittsburg",            "CA"): "Oakland-Hayward-Berkeley",
    ("martinez",             "CA"): "Oakland-Hayward-Berkeley",
    ("el cerrito",           "CA"): "Oakland-Hayward-Berkeley",
    ("castro valley",        "CA"): "Oakland-Hayward-Berkeley",
    # San Diego
    ("san diego",            "CA"): "San Diego",
    ("chula vista",          "CA"): "San Diego",
    ("el cajon",             "CA"): "San Diego",
    ("escondido",            "CA"): "San Diego",
    ("oceanside",            "CA"): "San Diego",
    ("carlsbad",             "CA"): "San Diego",
    ("santee",               "CA"): "San Diego",
    ("la mesa",              "CA"): "San Diego",
    ("vista",                "CA"): "San Diego",
    ("san marcos",           "CA"): "San Diego",
    ("poway",                "CA"): "San Diego",
    ("encinitas",            "CA"): "San Diego",
    ("national city",        "CA"): "San Diego",
    ("coronado",             "CA"): "San Diego",
    ("del mar",              "CA"): "San Diego",
    ("lemon grove",          "CA"): "San Diego",
    # Inland Empire
    ("riverside",            "CA"): "Riverside-San Bernardino",
    ("san bernardino",       "CA"): "Riverside-San Bernardino",
    ("ontario",              "CA"): "Riverside-San Bernardino",
    ("moreno valley",        "CA"): "Riverside-San Bernardino",
    ("fontana",              "CA"): "Riverside-San Bernardino",
    ("rancho cucamonga",     "CA"): "Riverside-San Bernardino",
    ("corona",               "CA"): "Riverside-San Bernardino",
    ("murrieta",             "CA"): "Riverside-San Bernardino",
    ("temecula",             "CA"): "Riverside-San Bernardino",
    ("victorville",          "CA"): "Riverside-San Bernardino",
    ("rialto",               "CA"): "Riverside-San Bernardino",
    ("hesperia",             "CA"): "Riverside-San Bernardino",
    ("ontario",              "CA"): "Riverside-San Bernardino",
    ("perris",               "CA"): "Riverside-San Bernardino",
    ("hemet",                "CA"): "Riverside-San Bernardino",
    ("indio",                "CA"): "Riverside-San Bernardino",
    ("palm springs",         "CA"): "Riverside-San Bernardino",
    ("palm desert",          "CA"): "Riverside-San Bernardino",
    ("redlands",             "CA"): "Riverside-San Bernardino",
    ("upland",               "CA"): "Riverside-San Bernardino",
    ("chino",                "CA"): "Riverside-San Bernardino",
    ("chino hills",          "CA"): "Riverside-San Bernardino",
    ("montclair",            "CA"): "Riverside-San Bernardino",
    # Ventura County
    ("oxnard",               "CA"): "Oxnard-Thousand Oaks",
    ("thousand oaks",        "CA"): "Oxnard-Thousand Oaks",
    ("ventura",              "CA"): "Oxnard-Thousand Oaks",
    ("camarillo",            "CA"): "Oxnard-Thousand Oaks",
    ("simi valley",          "CA"): "Oxnard-Thousand Oaks",
    ("moorpark",             "CA"): "Oxnard-Thousand Oaks",
    # Sacramento
    ("sacramento",           "CA"): "Sacramento",
    ("elk grove",            "CA"): "Sacramento",
    ("roseville",            "CA"): "Sacramento",
    ("folsom",               "CA"): "Sacramento",
    ("rocklin",              "CA"): "Sacramento",
    ("lincoln",              "CA"): "Sacramento",
    ("citrus heights",       "CA"): "Sacramento",
    ("rancho cordova",       "CA"): "Sacramento",
    ("west sacramento",      "CA"): "Sacramento",
    ("davis",                "CA"): "Sacramento",
    ("woodland",             "CA"): "Sacramento",
    ("vacaville",            "CA"): "Sacramento",
    # Other CA
    ("santa barbara",        "CA"): "Santa Maria-Santa Barbara",
    ("santa maria",          "CA"): "Santa Maria-Santa Barbara",
    ("lompoc",               "CA"): "Santa Maria-Santa Barbara",
    ("santa rosa",           "CA"): "Santa Rosa",
    ("petaluma",             "CA"): "Santa Rosa",
    ("rohnert park",         "CA"): "Santa Rosa",
    ("vallejo",              "CA"): "Vallejo/Fairfield/Napa",
    ("fairfield",            "CA"): "Vallejo/Fairfield/Napa",
    ("napa",                 "CA"): "Vallejo/Fairfield/Napa",
    ("benicia",              "CA"): "Vallejo/Fairfield/Napa",
    ("fresno",               "CA"): "Fresno",
    ("clovis",               "CA"): "Fresno",
    ("bakersfield",          "CA"): "Bakersfield",
    ("stockton",             "CA"): "Stockton",
    ("modesto",              "CA"): "Modesto",
    ("turlock",              "CA"): "Modesto",
    ("visalia",              "CA"): "Visalia-Porterville",
    ("reno",                 "NV"): "Reno",
    ("sparks",               "NV"): "Reno",
    # ── Texas ───────────────────────────────────────────────────────────────────
    ("dallas",               "TX"): "Dallas-Plano-Irving",
    ("plano",                "TX"): "Dallas-Plano-Irving",
    ("irving",               "TX"): "Dallas-Plano-Irving",
    ("garland",              "TX"): "Dallas-Plano-Irving",
    ("mesquite",             "TX"): "Dallas-Plano-Irving",
    ("richardson",           "TX"): "Dallas-Plano-Irving",
    ("frisco",               "TX"): "Dallas-Plano-Irving",
    ("mckinney",             "TX"): "Dallas-Plano-Irving",
    ("allen",                "TX"): "Dallas-Plano-Irving",
    ("denton",               "TX"): "Dallas-Plano-Irving",
    ("carrollton",           "TX"): "Dallas-Plano-Irving",
    ("lewisville",           "TX"): "Dallas-Plano-Irving",
    ("grand prairie",        "TX"): "Dallas-Plano-Irving",
    ("addison",              "TX"): "Dallas-Plano-Irving",
    ("farmers branch",       "TX"): "Dallas-Plano-Irving",
    ("rowlett",              "TX"): "Dallas-Plano-Irving",
    ("sachse",               "TX"): "Dallas-Plano-Irving",
    ("wylie",                "TX"): "Dallas-Plano-Irving",
    ("cedar hill",           "TX"): "Dallas-Plano-Irving",
    ("desoto",               "TX"): "Dallas-Plano-Irving",
    ("duncanville",          "TX"): "Dallas-Plano-Irving",
    ("lancaster",            "TX"): "Dallas-Plano-Irving",
    ("flower mound",         "TX"): "Dallas-Plano-Irving",
    ("the colony",           "TX"): "Dallas-Plano-Irving",
    ("little elm",           "TX"): "Dallas-Plano-Irving",
    ("prosper",              "TX"): "Dallas-Plano-Irving",
    ("celina",               "TX"): "Dallas-Plano-Irving",
    ("rockwall",             "TX"): "Dallas-Plano-Irving",
    ("forney",               "TX"): "Dallas-Plano-Irving",
    ("coppell",              "TX"): "Dallas-Plano-Irving",
    ("colleyville",          "TX"): "Ft. Worth-Arlington",
    ("southlake",            "TX"): "Ft. Worth-Arlington",
    ("grapevine",            "TX"): "Ft. Worth-Arlington",
    ("fort worth",           "TX"): "Ft. Worth-Arlington",
    ("arlington",            "TX"): "Ft. Worth-Arlington",
    ("north richland hills", "TX"): "Ft. Worth-Arlington",
    ("haltom city",          "TX"): "Ft. Worth-Arlington",
    ("euless",               "TX"): "Ft. Worth-Arlington",
    ("bedford",              "TX"): "Ft. Worth-Arlington",
    ("keller",               "TX"): "Ft. Worth-Arlington",
    ("mansfield",            "TX"): "Ft. Worth-Arlington",
    ("burleson",             "TX"): "Ft. Worth-Arlington",
    ("cleburne",             "TX"): "Ft. Worth-Arlington",
    ("watauga",              "TX"): "Ft. Worth-Arlington",
    ("houston",              "TX"): "Houston",
    ("sugar land",           "TX"): "Houston",
    ("the woodlands",        "TX"): "Houston",
    ("pearland",             "TX"): "Houston",
    ("pasadena",             "TX"): "Houston",
    ("league city",          "TX"): "Houston",
    ("katy",                 "TX"): "Houston",
    ("baytown",              "TX"): "Houston",
    ("missouri city",        "TX"): "Houston",
    ("friendswood",          "TX"): "Houston",
    ("conroe",               "TX"): "Houston",
    ("spring",               "TX"): "Houston",
    ("humble",               "TX"): "Houston",
    ("cypress",              "TX"): "Houston",
    ("atascocita",           "TX"): "Houston",
    ("stafford",             "TX"): "Houston",
    ("richmond",             "TX"): "Houston",
    ("rosenberg",            "TX"): "Houston",
    ("austin",               "TX"): "Austin",
    ("cedar park",           "TX"): "Austin",
    ("round rock",           "TX"): "Austin",
    ("pflugerville",         "TX"): "Austin",
    ("georgetown",           "TX"): "Austin",
    ("leander",              "TX"): "Austin",
    ("kyle",                 "TX"): "Austin",
    ("buda",                 "TX"): "Austin",
    ("bee cave",             "TX"): "Austin",
    ("lakeway",              "TX"): "Austin",
    ("san antonio",          "TX"): "San Antonio",
    ("new braunfels",        "TX"): "San Antonio",
    ("schertz",              "TX"): "San Antonio",
    ("cibolo",               "TX"): "San Antonio",
    ("san marcos",           "TX"): "San Antonio",
    ("el paso",              "TX"): "El Paso",
    ("mcallen",              "TX"): "McAllen",
    ("edinburg",             "TX"): "McAllen",
    ("pharr",                "TX"): "McAllen",
    ("mission",              "TX"): "McAllen",
    # ── Florida ─────────────────────────────────────────────────────────────────
    ("miami",                "FL"): "Miami-Kendall",
    ("kendall",              "FL"): "Miami-Kendall",
    ("hialeah",              "FL"): "Miami-Kendall",
    ("doral",                "FL"): "Miami-Kendall",
    ("homestead",            "FL"): "Miami-Kendall",
    ("miami gardens",        "FL"): "Miami-Kendall",
    ("miami beach",          "FL"): "Miami-Kendall",
    ("coral gables",         "FL"): "Miami-Kendall",
    ("aventura",             "FL"): "Miami-Kendall",
    ("north miami",          "FL"): "Miami-Kendall",
    ("cutler bay",           "FL"): "Miami-Kendall",
    ("opa locka",            "FL"): "Miami-Kendall",
    ("sweetwater",           "FL"): "Miami-Kendall",
    ("fort lauderdale",      "FL"): "Ft. Lauderdale-Pompano",
    ("pompano beach",        "FL"): "Ft. Lauderdale-Pompano",
    ("hollywood",            "FL"): "Ft. Lauderdale-Pompano",
    ("coral springs",        "FL"): "Ft. Lauderdale-Pompano",
    ("miramar",              "FL"): "Ft. Lauderdale-Pompano",
    ("pembroke pines",       "FL"): "Ft. Lauderdale-Pompano",
    ("davie",                "FL"): "Ft. Lauderdale-Pompano",
    ("plantation",           "FL"): "Ft. Lauderdale-Pompano",
    ("sunrise",              "FL"): "Ft. Lauderdale-Pompano",
    ("lauderhill",           "FL"): "Ft. Lauderdale-Pompano",
    ("deerfield beach",      "FL"): "Ft. Lauderdale-Pompano",
    ("margate",              "FL"): "Ft. Lauderdale-Pompano",
    ("tamarac",              "FL"): "Ft. Lauderdale-Pompano",
    ("coconut creek",        "FL"): "Ft. Lauderdale-Pompano",
    ("hallandale beach",     "FL"): "Ft. Lauderdale-Pompano",
    ("west palm beach",      "FL"): "West Palm-Boca-Delray",
    ("boca raton",           "FL"): "West Palm-Boca-Delray",
    ("delray beach",         "FL"): "West Palm-Boca-Delray",
    ("boynton beach",        "FL"): "West Palm-Boca-Delray",
    ("lake worth",           "FL"): "West Palm-Boca-Delray",
    ("palm beach gardens",   "FL"): "West Palm-Boca-Delray",
    ("jupiter",              "FL"): "West Palm-Boca-Delray",
    ("riviera beach",        "FL"): "West Palm-Boca-Delray",
    ("royal palm beach",     "FL"): "West Palm-Boca-Delray",
    ("wellington",           "FL"): "West Palm-Boca-Delray",
    ("orlando",              "FL"): "Orlando",
    ("kissimmee",            "FL"): "Orlando",
    ("sanford",              "FL"): "Orlando",
    ("apopka",               "FL"): "Orlando",
    ("altamonte springs",    "FL"): "Orlando",
    ("winter garden",        "FL"): "Orlando",
    ("ocoee",                "FL"): "Orlando",
    ("clermont",             "FL"): "Orlando",
    ("casselberry",          "FL"): "Orlando",
    ("winter park",          "FL"): "Orlando",
    ("maitland",             "FL"): "Orlando",
    ("oviedo",               "FL"): "Orlando",
    ("longwood",             "FL"): "Orlando",
    ("lake mary",            "FL"): "Orlando",
    ("daytona beach",        "FL"): "Daytona Beach",
    ("port orange",          "FL"): "Daytona Beach",
    ("deltona",              "FL"): "Daytona Beach",
    ("jacksonville",         "FL"): "Jacksonville",
    ("jacksonville beach",   "FL"): "Jacksonville",
    ("neptune beach",        "FL"): "Jacksonville",
    ("orange park",          "FL"): "Jacksonville",
    ("fleming island",       "FL"): "Jacksonville",
    ("mandarin",             "FL"): "Jacksonville",
    ("tampa",                "FL"): "Tampa-St. Pete",
    ("st. pete",             "FL"): "Tampa-St. Pete",
    ("st. petersburg",       "FL"): "Tampa-St. Pete",
    ("clearwater",           "FL"): "Tampa-St. Pete",
    ("brandon",              "FL"): "Tampa-St. Pete",
    ("riverview",            "FL"): "Tampa-St. Pete",
    ("wesley chapel",        "FL"): "Tampa-St. Pete",
    ("new port richey",      "FL"): "Tampa-St. Pete",
    ("port richey",          "FL"): "Tampa-St. Pete",
    ("land o lakes",         "FL"): "Tampa-St. Pete",
    ("lutz",                 "FL"): "Tampa-St. Pete",
    ("dunedin",              "FL"): "Tampa-St. Pete",
    ("safety harbor",        "FL"): "Tampa-St. Pete",
    ("tarpon springs",       "FL"): "Tampa-St. Pete",
    ("palm harbor",          "FL"): "Tampa-St. Pete",
    ("largo",                "FL"): "Tampa-St. Pete",
    ("pinellas park",        "FL"): "Tampa-St. Pete",
    ("seminole",             "FL"): "Tampa-St. Pete",
    ("temple terrace",       "FL"): "Tampa-St. Pete",
    ("palm bay",             "FL"): "Palm Bay-Melbourne",
    ("melbourne",            "FL"): "Palm Bay-Melbourne",
    ("naples",               "FL"): "Naples-Marco Island",
    ("marco island",         "FL"): "Naples-Marco Island",
    ("sarasota",             "FL"): "N. Port-Sarasota-Bradenton",
    ("bradenton",            "FL"): "N. Port-Sarasota-Bradenton",
    ("north port",           "FL"): "N. Port-Sarasota-Bradenton",
    ("venice",               "FL"): "N. Port-Sarasota-Bradenton",
    ("cape coral",           "FL"): "Cape Coral-Ft. Myers",
    ("fort myers",           "FL"): "Cape Coral-Ft. Myers",
    ("bonita springs",       "FL"): "Cape Coral-Ft. Myers",
    ("tallahassee",          "FL"): "Tallahassee",
    ("gainesville",          "FL"): "Gainesville",
    ("pensacola",            "FL"): "Pensacola",
    ("destin",               "FL"): "Pensacola",
    ("fort walton beach",    "FL"): "Pensacola",
    ("lakeland",             "FL"): "Lakeland-Winter Haven",
    ("winter haven",         "FL"): "Lakeland-Winter Haven",
    # ── Georgia ─────────────────────────────────────────────────────────────────
    ("atlanta",              "GA"): "Atlanta",
    ("marietta",             "GA"): "Atlanta",
    ("sandy springs",        "GA"): "Atlanta",
    ("roswell",              "GA"): "Atlanta",
    ("johns creek",          "GA"): "Atlanta",
    ("alpharetta",           "GA"): "Atlanta",
    ("smyrna",               "GA"): "Atlanta",
    ("kennesaw",             "GA"): "Atlanta",
    ("peachtree city",       "GA"): "Atlanta",
    ("rome",                 "GA"): "Atlanta",
    ("duluth",               "GA"): "Atlanta",
    ("lawrenceville",        "GA"): "Atlanta",
    ("norcross",             "GA"): "Atlanta",
    ("tucker",               "GA"): "Atlanta",
    ("decatur",              "GA"): "Atlanta",
    ("east point",           "GA"): "Atlanta",
    ("college park",         "GA"): "Atlanta",
    ("union city",           "GA"): "Atlanta",
    ("fayetteville",         "GA"): "Atlanta",
    ("stockbridge",          "GA"): "Atlanta",
    ("mcdonough",            "GA"): "Atlanta",
    ("conyers",              "GA"): "Atlanta",
    ("covington",            "GA"): "Atlanta",
    ("cumming",              "GA"): "Atlanta",
    ("canton",               "GA"): "Atlanta",
    ("woodstock",            "GA"): "Atlanta",
    ("acworth",              "GA"): "Atlanta",
    ("powder springs",       "GA"): "Atlanta",
    ("douglasville",         "GA"): "Atlanta",
    ("savannah",             "GA"): "Savannah",
    ("pooler",               "GA"): "Savannah",
    ("richmond hill",        "GA"): "Savannah",
    ("augusta",              "GA"): "Augusta",
    ("evans",                "GA"): "Augusta",
    ("columbus",             "GA"): "Columbus-Phenix City",
    # ── Illinois ────────────────────────────────────────────────────────────────
    ("chicago",              "IL"): "Chicago",
    ("aurora",               "IL"): "Chicago",
    ("naperville",           "IL"): "Chicago",
    ("rockford",             "IL"): "Chicago",
    ("joliet",               "IL"): "Chicago",
    ("evanston",             "IL"): "Chicago",
    ("waukegan",             "IL"): "Chicago",
    ("elgin",                "IL"): "Chicago",
    ("schaumburg",           "IL"): "Chicago",
    ("bolingbrook",          "IL"): "Chicago",
    ("arlington heights",    "IL"): "Chicago",
    ("palatine",             "IL"): "Chicago",
    ("wheeling",             "IL"): "Chicago",
    ("des plaines",          "IL"): "Chicago",
    ("elk grove village",    "IL"): "Chicago",
    ("glenview",             "IL"): "Chicago",
    ("oak park",             "IL"): "Chicago",
    ("berwyn",               "IL"): "Chicago",
    ("cicero",               "IL"): "Chicago",
    ("downers grove",        "IL"): "Chicago",
    ("lisle",                "IL"): "Chicago",
    ("oak brook",            "IL"): "Chicago",
    ("lombard",              "IL"): "Chicago",
    ("wheaton",              "IL"): "Chicago",
    ("glen ellyn",           "IL"): "Chicago",
    ("carol stream",         "IL"): "Chicago",
    ("bartlett",             "IL"): "Chicago",
    ("streamwood",           "IL"): "Chicago",
    ("hanover park",         "IL"): "Chicago",
    ("glendale heights",     "IL"): "Chicago",
    ("addison",              "IL"): "Chicago",
    ("villa park",           "IL"): "Chicago",
    ("elmhurst",             "IL"): "Chicago",
    ("oak lawn",             "IL"): "Chicago",
    ("orland park",          "IL"): "Chicago",
    ("tinley park",          "IL"): "Chicago",
    ("mokena",               "IL"): "Chicago",
    ("frankfort",            "IL"): "Chicago",
    ("new lenox",            "IL"): "Chicago",
    ("lockport",             "IL"): "Chicago",
    ("romeoville",           "IL"): "Chicago",
    ("plainfield",           "IL"): "Chicago",
    ("oswego",               "IL"): "Chicago",
    ("yorkville",            "IL"): "Chicago",
    ("crystal lake",         "IL"): "Chicago",
    ("algonquin",            "IL"): "Chicago",
    ("round lake beach",     "IL"): "Chicago",
    ("mundelein",            "IL"): "Chicago",
    ("libertyville",         "IL"): "Chicago",
    ("gurnee",               "IL"): "Chicago",
    ("lake zurich",          "IL"): "Chicago",
    ("buffalo grove",        "IL"): "Chicago",
    ("vernon hills",         "IL"): "Chicago",
    ("north chicago",        "IL"): "Chicago",
    ("zion",                 "IL"): "Chicago",
    ("highland park",        "IL"): "Chicago",
    ("lake forest",          "IL"): "Chicago",
    # ── Colorado ────────────────────────────────────────────────────────────────
    ("denver",               "CO"): "Denver",
    ("aurora",               "CO"): "Denver",
    ("lakewood",             "CO"): "Denver",
    ("thornton",             "CO"): "Denver",
    ("arvada",               "CO"): "Denver",
    ("westminster",          "CO"): "Denver",
    ("centennial",           "CO"): "Denver",
    ("highlands ranch",      "CO"): "Denver",
    ("lone tree",            "CO"): "Denver",
    ("littleton",            "CO"): "Denver",
    ("englewood",            "CO"): "Denver",
    ("parker",               "CO"): "Denver",
    ("castle rock",          "CO"): "Denver",
    ("castle pines",         "CO"): "Denver",
    ("wheat ridge",          "CO"): "Denver",
    ("golden",               "CO"): "Denver",
    ("commerce city",        "CO"): "Denver",
    ("federal heights",      "CO"): "Denver",
    ("northglenn",           "CO"): "Denver",
    ("broomfield",           "CO"): "Denver",
    ("boulder",              "CO"): "Boulder",
    ("longmont",             "CO"): "Boulder",
    ("lafayette",            "CO"): "Boulder",
    ("erie",                 "CO"): "Boulder",
    ("superior",             "CO"): "Boulder",
    ("louisville",           "CO"): "Boulder",
    ("fort collins",         "CO"): "Ft. Collins",
    ("loveland",             "CO"): "Ft. Collins",
    ("greeley",              "CO"): "Greeley",
    ("evans",                "CO"): "Greeley",
    ("colorado springs",     "CO"): "Colorado Springs",
    ("pueblo",               "CO"): "Colorado Springs",
    # ── Arizona ─────────────────────────────────────────────────────────────────
    ("phoenix",              "AZ"): "Phoenix",
    ("scottsdale",           "AZ"): "Phoenix",
    ("tempe",                "AZ"): "Phoenix",
    ("mesa",                 "AZ"): "Phoenix",
    ("chandler",             "AZ"): "Phoenix",
    ("gilbert",              "AZ"): "Phoenix",
    ("glendale",             "AZ"): "Phoenix",
    ("peoria",               "AZ"): "Phoenix",
    ("avondale",             "AZ"): "Phoenix",
    ("goodyear",             "AZ"): "Phoenix",
    ("surprise",             "AZ"): "Phoenix",
    ("buckeye",              "AZ"): "Phoenix",
    ("queen creek",          "AZ"): "Phoenix",
    ("maricopa",             "AZ"): "Phoenix",
    ("apache junction",      "AZ"): "Phoenix",
    ("cave creek",           "AZ"): "Phoenix",
    ("fountain hills",       "AZ"): "Phoenix",
    ("paradise valley",      "AZ"): "Phoenix",
    ("el mirage",            "AZ"): "Phoenix",
    ("tolleson",             "AZ"): "Phoenix",
    ("litchfield park",      "AZ"): "Phoenix",
    ("tucson",               "AZ"): "Tucson",
    ("marana",               "AZ"): "Tucson",
    ("oro valley",           "AZ"): "Tucson",
    ("sahuarita",            "AZ"): "Tucson",
    # ── Nevada ──────────────────────────────────────────────────────────────────
    ("las vegas",            "NV"): "Las Vegas",
    ("henderson",            "NV"): "Las Vegas",
    ("north las vegas",      "NV"): "Las Vegas",
    ("summerlin",            "NV"): "Las Vegas",
    ("enterprise",           "NV"): "Las Vegas",
    ("boulder city",         "NV"): "Las Vegas",
    ("mesquite",             "NV"): "Las Vegas",
    # ── Washington ──────────────────────────────────────────────────────────────
    ("seattle",              "WA"): "Seattle",
    ("bellevue",             "WA"): "Seattle",
    ("redmond",              "WA"): "Seattle",
    ("kirkland",             "WA"): "Seattle",
    ("renton",               "WA"): "Seattle",
    ("issaquah",             "WA"): "Seattle",
    ("kent",                 "WA"): "Seattle",
    ("federal way",          "WA"): "Seattle",
    ("auburn",               "WA"): "Seattle",
    ("shoreline",            "WA"): "Seattle",
    ("burien",               "WA"): "Seattle",
    ("tukwila",              "WA"): "Seattle",
    ("bothell",              "WA"): "Seattle",
    ("lynnwood",             "WA"): "Seattle",
    ("mountlake terrace",    "WA"): "Seattle",
    ("edmonds",              "WA"): "Seattle",
    ("kenmore",              "WA"): "Seattle",
    ("sammamish",            "WA"): "Seattle",
    ("mercer island",        "WA"): "Seattle",
    ("newcastle",            "WA"): "Seattle",
    ("covington",            "WA"): "Seattle",
    ("maple valley",         "WA"): "Seattle",
    ("black diamond",        "WA"): "Seattle",
    ("des moines",           "WA"): "Seattle",
    ("normandy park",        "WA"): "Seattle",
    ("seatac",               "WA"): "Seattle",
    ("mukilteo",             "WA"): "Seattle",
    ("mill creek",           "WA"): "Seattle",
    ("everett",              "WA"): "Seattle",
    ("marysville",           "WA"): "Seattle",
    ("snohomish",            "WA"): "Seattle",
    ("monroe",               "WA"): "Seattle",
    ("tacoma",               "WA"): "Tacoma-Lakewood",
    ("lakewood",             "WA"): "Tacoma-Lakewood",
    ("university place",     "WA"): "Tacoma-Lakewood",
    ("puyallup",             "WA"): "Tacoma-Lakewood",
    ("bonney lake",          "WA"): "Tacoma-Lakewood",
    ("fife",                 "WA"): "Tacoma-Lakewood",
    ("sumner",               "WA"): "Tacoma-Lakewood",
    ("auburn",               "WA"): "Tacoma-Lakewood",
    ("olympia",              "WA"): "Olympia-Lacey-Tumwater",
    ("lacey",                "WA"): "Olympia-Lacey-Tumwater",
    ("tumwater",             "WA"): "Olympia-Lacey-Tumwater",
    ("spokane",              "WA"): "Spokane",
    ("spokane valley",       "WA"): "Spokane",
    # ── Oregon ──────────────────────────────────────────────────────────────────
    ("portland",             "OR"): "Portland",
    ("beaverton",            "OR"): "Portland",
    ("lake oswego",          "OR"): "Portland",
    ("gresham",              "OR"): "Portland",
    ("hillsboro",            "OR"): "Portland",
    ("tualatin",             "OR"): "Portland",
    ("tigard",               "OR"): "Portland",
    ("milwaukie",            "OR"): "Portland",
    ("happy valley",         "OR"): "Portland",
    ("west linn",            "OR"): "Portland",
    ("oregon city",          "OR"): "Portland",
    ("wilsonville",          "OR"): "Portland",
    ("canby",                "OR"): "Portland",
    ("sherwood",             "OR"): "Portland",
    ("newberg",              "OR"): "Portland",
    ("mcminnville",          "OR"): "Portland",
    ("troutdale",            "OR"): "Portland",
    ("fairview",             "OR"): "Portland",
    ("wood village",         "OR"): "Portland",
    ("north plains",         "OR"): "Portland",
    ("cornelius",            "OR"): "Portland",
    ("forest grove",         "OR"): "Portland",
    ("vancouver",            "WA"): "Portland",
    ("camas",                "WA"): "Portland",
    ("battle ground",        "WA"): "Portland",
    ("ridgefield",           "WA"): "Portland",
    ("washougal",            "WA"): "Portland",
    ("eugene",               "OR"): "Eugene",
    ("springfield",          "OR"): "Eugene",
    ("corvallis",            "OR"): "Corvallis",
    ("salem",                "OR"): "Salem",
    # ── Utah ────────────────────────────────────────────────────────────────────
    ("salt lake city",       "UT"): "Salt Lake City",
    ("west valley city",     "UT"): "Salt Lake City",
    ("west jordan",          "UT"): "Salt Lake City",
    ("sandy",                "UT"): "Salt Lake City",
    ("south jordan",         "UT"): "Salt Lake City",
    ("taylorsville",         "UT"): "Salt Lake City",
    ("murray",               "UT"): "Salt Lake City",
    ("millcreek",            "UT"): "Salt Lake City",
    ("kearns",               "UT"): "Salt Lake City",
    ("riverton",             "UT"): "Salt Lake City",
    ("herriman",             "UT"): "Salt Lake City",
    ("draper",               "UT"): "Salt Lake City",
    ("cottonwood heights",   "UT"): "Salt Lake City",
    ("holladay",             "UT"): "Salt Lake City",
    ("midvale",              "UT"): "Salt Lake City",
    ("provo",                "UT"): "Provo-Orem",
    ("orem",                 "UT"): "Provo-Orem",
    ("lehi",                 "UT"): "Provo-Orem",
    ("american fork",        "UT"): "Provo-Orem",
    ("pleasant grove",       "UT"): "Provo-Orem",
    ("lindon",               "UT"): "Provo-Orem",
    ("spanish fork",         "UT"): "Provo-Orem",
    ("ogden",                "UT"): "Ogden-Clearfield",
    ("layton",               "UT"): "Ogden-Clearfield",
    ("clearfield",           "UT"): "Ogden-Clearfield",
    ("bountiful",            "UT"): "Ogden-Clearfield",
    ("north salt lake",      "UT"): "Ogden-Clearfield",
    ("kaysville",            "UT"): "Ogden-Clearfield",
    ("farmington",           "UT"): "Ogden-Clearfield",
    ("clinton",              "UT"): "Ogden-Clearfield",
    ("syracuse",             "UT"): "Ogden-Clearfield",
    # ── North Carolina ──────────────────────────────────────────────────────────
    ("charlotte",            "NC"): "Charlotte",
    ("concord",              "NC"): "Charlotte",
    ("gastonia",             "NC"): "Charlotte",
    ("huntersville",         "NC"): "Charlotte",
    ("kannapolis",           "NC"): "Charlotte",
    ("matthews",             "NC"): "Charlotte",
    ("cornelius",            "NC"): "Charlotte",
    ("davidson",             "NC"): "Charlotte",
    ("mooresville",          "NC"): "Charlotte",
    ("lake norman",          "NC"): "Charlotte",
    ("mint hill",            "NC"): "Charlotte",
    ("indian trail",         "NC"): "Charlotte",
    ("stallings",            "NC"): "Charlotte",
    ("monroe",               "NC"): "Charlotte",
    ("belmont",              "NC"): "Charlotte",
    ("rock hill",            "SC"): "Charlotte",
    ("fort mill",            "SC"): "Charlotte",
    ("tega cay",             "SC"): "Charlotte",
    ("raleigh",              "NC"): "Raleigh",
    ("durham",               "NC"): "Raleigh",
    ("cary",                 "NC"): "Raleigh",
    ("chapel hill",          "NC"): "Raleigh",
    ("morrisville",          "NC"): "Raleigh",
    ("apex",                 "NC"): "Raleigh",
    ("wake forest",          "NC"): "Raleigh",
    ("garner",               "NC"): "Raleigh",
    ("clayton",              "NC"): "Raleigh",
    ("fuquay varina",        "NC"): "Raleigh",
    ("holly springs",        "NC"): "Raleigh",
    ("rolesville",           "NC"): "Raleigh",
    ("greensboro",           "NC"): "Greensboro",
    ("high point",           "NC"): "Greensboro",
    ("winston-salem",        "NC"): "Winston-Salem",
    ("wilmington",           "NC"): "Wilmington",
    ("asheville",            "NC"): "Asheville",
    # ── Tennessee ───────────────────────────────────────────────────────────────
    ("nashville",            "TN"): "Nashville",
    ("murfreesboro",         "TN"): "Nashville",
    ("franklin",             "TN"): "Nashville",
    ("brentwood",            "TN"): "Nashville",
    ("hendersonville",       "TN"): "Nashville",
    ("smyrna",               "TN"): "Nashville",
    ("la vergne",            "TN"): "Nashville",
    ("gallatin",             "TN"): "Nashville",
    ("lebanon",              "TN"): "Nashville",
    ("spring hill",          "TN"): "Nashville",
    ("mt. juliet",           "TN"): "Nashville",
    ("columbia",             "TN"): "Nashville",
    ("clarksville",          "TN"): "Clarksville",
    ("memphis",              "TN"): "Memphis",
    ("germantown",           "TN"): "Memphis",
    ("collierville",         "TN"): "Memphis",
    ("bartlett",             "TN"): "Memphis",
    ("southaven",            "MS"): "Memphis",
    ("olive branch",         "MS"): "Memphis",
    ("knoxville",            "TN"): "Knoxville",
    ("maryville",            "TN"): "Knoxville",
    ("chattanooga",          "TN"): "Chattanooga",
    # ── South Carolina ──────────────────────────────────────────────────────────
    ("charleston",           "SC"): "Charleston",
    ("north charleston",     "SC"): "Charleston",
    ("mount pleasant",       "SC"): "Charleston",
    ("summerville",          "SC"): "Charleston",
    ("goose creek",          "SC"): "Charleston",
    ("hanahan",              "SC"): "Charleston",
    ("greenville",           "SC"): "Greenville",
    ("spartanburg",          "SC"): "Greenville",
    ("greer",                "SC"): "Greenville",
    ("mauldin",              "SC"): "Greenville",
    ("simpsonville",         "SC"): "Greenville",
    ("taylors",              "SC"): "Greenville",
    ("columbia",             "SC"): "Columbia",
    ("lexington",            "SC"): "Columbia",
    ("irmo",                 "SC"): "Columbia",
    ("myrtle beach",         "SC"): "Myrtle Beach",
    # ── Virginia / DC Metro ──────────────────────────────────────────────────────
    ("arlington",            "VA"): "Washington-Northern VA",
    ("alexandria",           "VA"): "Washington-Northern VA",
    ("falls church",         "VA"): "Washington-Northern VA",
    ("fairfax",              "VA"): "Washington-Northern VA",
    ("reston",               "VA"): "Washington-Northern VA",
    ("herndon",              "VA"): "Washington-Northern VA",
    ("vienna",               "VA"): "Washington-Northern VA",
    ("mclean",               "VA"): "Washington-Northern VA",
    ("tysons",               "VA"): "Washington-Northern VA",
    ("annandale",            "VA"): "Washington-Northern VA",
    ("springfield",          "VA"): "Washington-Northern VA",
    ("burke",                "VA"): "Washington-Northern VA",
    ("centreville",          "VA"): "Washington-Northern VA",
    ("chantilly",            "VA"): "Washington-Northern VA",
    ("loudoun",              "VA"): "Washington-Northern VA",
    ("ashburn",              "VA"): "Washington-Northern VA",
    ("leesburg",             "VA"): "Washington-Northern VA",
    ("sterling",             "VA"): "Washington-Northern VA",
    ("manassas",             "VA"): "Washington-Northern VA",
    ("woodbridge",           "VA"): "Washington-Northern VA",
    ("dale city",            "VA"): "Washington-Northern VA",
    ("lake ridge",           "VA"): "Washington-Northern VA",
    ("washington",           "DC"): "Washington-Northern VA",
    ("richmond",             "VA"): "Richmond",
    ("henrico",              "VA"): "Richmond",
    ("chesterfield",         "VA"): "Richmond",
    ("chester",              "VA"): "Richmond",
    ("midlothian",           "VA"): "Richmond",
    ("glen allen",           "VA"): "Richmond",
    ("mechanicsville",       "VA"): "Richmond",
    ("norfolk",              "VA"): "Norfolk-Virginia Beach",
    ("virginia beach",       "VA"): "Norfolk-Virginia Beach",
    ("chesapeake",           "VA"): "Norfolk-Virginia Beach",
    ("hampton",              "VA"): "Norfolk-Virginia Beach",
    ("newport news",         "VA"): "Norfolk-Virginia Beach",
    ("suffolk",              "VA"): "Norfolk-Virginia Beach",
    ("portsmouth",           "VA"): "Norfolk-Virginia Beach",
    # ── Maryland ────────────────────────────────────────────────────────────────
    ("baltimore",            "MD"): "Baltimore",
    ("columbia",             "MD"): "Baltimore",
    ("towson",               "MD"): "Baltimore",
    ("ellicott city",        "MD"): "Baltimore",
    ("bel air",              "MD"): "Baltimore",
    ("dundalk",              "MD"): "Baltimore",
    ("glen burnie",          "MD"): "Baltimore",
    ("annapolis",            "MD"): "Baltimore",
    ("severna park",         "MD"): "Baltimore",
    ("bowie",                "MD"): "Washington-Northern VA",
    ("rockville",            "MD"): "Washington-Northern VA",
    ("gaithersburg",         "MD"): "Washington-Northern VA",
    ("germantown",           "MD"): "Washington-Northern VA",
    ("silver spring",        "MD"): "Washington-Northern VA",
    ("bethesda",             "MD"): "Washington-Northern VA",
    ("chevy chase",          "MD"): "Washington-Northern VA",
    ("college park",         "MD"): "Washington-Northern VA",
    ("greenbelt",            "MD"): "Washington-Northern VA",
    ("hyattsville",          "MD"): "Washington-Northern VA",
    ("laurel",               "MD"): "Washington-Northern VA",
    ("upper marlboro",       "MD"): "Washington-Northern VA",
    ("waldorf",              "MD"): "Washington-Northern VA",
    ("la plata",             "MD"): "Washington-Northern VA",
    # ── New York ────────────────────────────────────────────────────────────────
    ("new york",             "NY"): "New York-White Plains",
    ("white plains",         "NY"): "New York-White Plains",
    ("yonkers",              "NY"): "New York-White Plains",
    ("bronx",                "NY"): "New York-White Plains",
    ("brooklyn",             "NY"): "New York-White Plains",
    ("queens",               "NY"): "New York-White Plains",
    ("staten island",        "NY"): "New York-White Plains",
    ("manhattan",            "NY"): "New York-White Plains",
    ("new rochelle",         "NY"): "New York-White Plains",
    ("mount vernon",         "NY"): "New York-White Plains",
    ("scarsdale",            "NY"): "New York-White Plains",
    ("mount kisco",          "NY"): "New York-White Plains",
    ("ossining",             "NY"): "New York-White Plains",
    ("peekskill",            "NY"): "New York-White Plains",
    ("tarrytown",            "NY"): "New York-White Plains",
    ("hempstead",            "NY"): "Nassau Co. - Suffolk Co.",
    ("brentwood",            "NY"): "Nassau Co. - Suffolk Co.",
    ("huntington",           "NY"): "Nassau Co. - Suffolk Co.",
    ("babylon",              "NY"): "Nassau Co. - Suffolk Co.",
    ("islip",                "NY"): "Nassau Co. - Suffolk Co.",
    ("smithtown",            "NY"): "Nassau Co. - Suffolk Co.",
    ("east meadow",          "NY"): "Nassau Co. - Suffolk Co.",
    ("uniondale",            "NY"): "Nassau Co. - Suffolk Co.",
    ("freeport",             "NY"): "Nassau Co. - Suffolk Co.",
    ("long beach",           "NY"): "Nassau Co. - Suffolk Co.",
    ("mineola",              "NY"): "Nassau Co. - Suffolk Co.",
    ("garden city",          "NY"): "Nassau Co. - Suffolk Co.",
    ("albany",               "NY"): "Albany",
    ("schenectady",          "NY"): "Albany",
    ("troy",                 "NY"): "Albany",
    ("buffalo",              "NY"): "Buffalo-Cheektowaga",
    ("cheektowaga",          "NY"): "Buffalo-Cheektowaga",
    ("niagara falls",        "NY"): "Buffalo-Cheektowaga",
    ("rochester",            "NY"): "Rochester",
    ("syracuse",             "NY"): "Syracuse",
    # ── New Jersey ──────────────────────────────────────────────────────────────
    ("newark",               "NJ"): "Newark-Jersey City",
    ("jersey city",          "NJ"): "Newark-Jersey City",
    ("paterson",             "NJ"): "Newark-Jersey City",
    ("elizabeth",            "NJ"): "Newark-Jersey City",
    ("clifton",              "NJ"): "Newark-Jersey City",
    ("trenton",              "NJ"): "Newark-Jersey City",
    ("camden",               "NJ"): "Newark-Jersey City",
    ("bayonne",              "NJ"): "Newark-Jersey City",
    ("east orange",          "NJ"): "Newark-Jersey City",
    ("irvington",            "NJ"): "Newark-Jersey City",
    ("hackensack",           "NJ"): "Newark-Jersey City",
    ("hoboken",              "NJ"): "Newark-Jersey City",
    ("union city",           "NJ"): "Newark-Jersey City",
    ("north bergen",         "NJ"): "Newark-Jersey City",
    ("west new york",        "NJ"): "Newark-Jersey City",
    ("woodbridge",           "NJ"): "Newark-Jersey City",
    ("edison",               "NJ"): "Newark-Jersey City",
    ("piscataway",           "NJ"): "Newark-Jersey City",
    ("new brunswick",        "NJ"): "Newark-Jersey City",
    ("parsippany",           "NJ"): "Newark-Jersey City",
    ("morristown",           "NJ"): "Newark-Jersey City",
    ("teaneck",              "NJ"): "Newark-Jersey City",
    ("princeton",            "NJ"): "Newark-Jersey City",
    # ── Connecticut ─────────────────────────────────────────────────────────────
    ("bridgeport",           "CT"): "Bridgeport-Stamford",
    ("stamford",             "CT"): "Bridgeport-Stamford",
    ("norwalk",              "CT"): "Bridgeport-Stamford",
    ("danbury",              "CT"): "Bridgeport-Stamford",
    ("new haven",            "CT"): "New Haven",
    ("hartford",             "CT"): "Hartford",
    ("west hartford",        "CT"): "Hartford",
    ("waterbury",            "CT"): "Hartford",
    ("new britain",          "CT"): "Hartford",
    # ── Massachusetts ───────────────────────────────────────────────────────────
    ("boston",               "MA"): "Boston",
    ("cambridge",            "MA"): "Boston",
    ("somerville",           "MA"): "Boston",
    ("quincy",               "MA"): "Boston",
    ("newton",               "MA"): "Boston",
    ("brookline",            "MA"): "Boston",
    ("malden",               "MA"): "Boston",
    ("medford",              "MA"): "Boston",
    ("waltham",              "MA"): "Boston",
    ("watertown",            "MA"): "Boston",
    ("arlington",            "MA"): "Boston",
    ("belmont",              "MA"): "Boston",
    ("woburn",               "MA"): "Boston",
    ("lynn",                 "MA"): "Boston",
    ("revere",               "MA"): "Boston",
    ("chelsea",              "MA"): "Boston",
    ("everett",              "MA"): "Boston",
    ("salem",                "MA"): "Boston",
    ("peabody",              "MA"): "Boston",
    ("beverly",              "MA"): "Boston",
    ("gloucester",           "MA"): "Boston",
    ("marblehead",           "MA"): "Boston",
    ("swampscott",           "MA"): "Boston",
    ("saugus",               "MA"): "Boston",
    ("melrose",              "MA"): "Boston",
    ("stoneham",             "MA"): "Boston",
    ("wakefield",            "MA"): "Boston",
    ("lexington",            "MA"): "Boston",
    ("concord",              "MA"): "Boston",
    ("bedford",              "MA"): "Boston",
    ("burlington",           "MA"): "Boston",
    ("wilmington",           "MA"): "Boston",
    ("reading",              "MA"): "Boston",
    ("andover",              "MA"): "Boston",
    ("lawrence",             "MA"): "Boston",
    ("lowell",               "MA"): "Boston",
    ("haverhill",            "MA"): "Boston",
    ("methuen",              "MA"): "Boston",
    ("westford",             "MA"): "Boston",
    ("chelmsford",           "MA"): "Boston",
    ("billerica",            "MA"): "Boston",
    ("tewksbury",            "MA"): "Boston",
    ("dracut",               "MA"): "Boston",
    ("braintree",            "MA"): "Boston",
    ("weymouth",             "MA"): "Boston",
    ("milton",               "MA"): "Boston",
    ("canton",               "MA"): "Boston",
    ("norwood",              "MA"): "Boston",
    ("dedham",               "MA"): "Boston",
    ("westwood",             "MA"): "Boston",
    ("needham",              "MA"): "Boston",
    ("wellesley",            "MA"): "Boston",
    ("natick",               "MA"): "Boston",
    ("framingham",           "MA"): "Boston",
    ("ashland",              "MA"): "Boston",
    ("hopkinton",            "MA"): "Boston",
    ("sudbury",              "MA"): "Boston",
    ("wayland",              "MA"): "Boston",
    ("weston",               "MA"): "Boston",
    ("worcester",            "MA"): "Worcester",
    ("springfield",          "MA"): "Springfield",
    ("chicopee",             "MA"): "Springfield",
    ("holyoke",              "MA"): "Springfield",
    # ── Pennsylvania ────────────────────────────────────────────────────────────
    ("philadelphia",         "PA"): "Philadelphia",
    ("allentown",            "PA"): "Philadelphia",
    ("bethlehem",            "PA"): "Philadelphia",
    ("reading",              "PA"): "Philadelphia",
    ("chester",              "PA"): "Philadelphia",
    ("norristown",           "PA"): "Philadelphia",
    ("king of prussia",      "PA"): "Philadelphia",
    ("conshohocken",         "PA"): "Philadelphia",
    ("lansdale",             "PA"): "Philadelphia",
    ("doylestown",           "PA"): "Philadelphia",
    ("wilmington",           "DE"): "Philadelphia",
    ("newark",               "DE"): "Philadelphia",
    ("pittsburgh",           "PA"): "Pittsburgh",
    ("bethel park",          "PA"): "Pittsburgh",
    ("mount lebanon",        "PA"): "Pittsburgh",
    ("monroeville",          "PA"): "Pittsburgh",
    ("cranberry township",   "PA"): "Pittsburgh",
    ("harrisburg",           "PA"): "Harrisburg",
    ("altoona",              "PA"): "Altoona",
    # ── Minnesota ───────────────────────────────────────────────────────────────
    ("minneapolis",          "MN"): "Minneapolis-St. Paul",
    ("st. paul",             "MN"): "Minneapolis-St. Paul",
    ("saint paul",           "MN"): "Minneapolis-St. Paul",
    ("bloomington",          "MN"): "Minneapolis-St. Paul",
    ("brooklyn park",        "MN"): "Minneapolis-St. Paul",
    ("plymouth",             "MN"): "Minneapolis-St. Paul",
    ("maple grove",          "MN"): "Minneapolis-St. Paul",
    ("woodbury",             "MN"): "Minneapolis-St. Paul",
    ("eden prairie",         "MN"): "Minneapolis-St. Paul",
    ("eagan",                "MN"): "Minneapolis-St. Paul",
    ("burnsville",           "MN"): "Minneapolis-St. Paul",
    ("apple valley",         "MN"): "Minneapolis-St. Paul",
    ("lakeville",            "MN"): "Minneapolis-St. Paul",
    ("coon rapids",          "MN"): "Minneapolis-St. Paul",
    ("brooklyn center",      "MN"): "Minneapolis-St. Paul",
    ("richfield",            "MN"): "Minneapolis-St. Paul",
    ("edina",                "MN"): "Minneapolis-St. Paul",
    ("minnetonka",           "MN"): "Minneapolis-St. Paul",
    ("golden valley",        "MN"): "Minneapolis-St. Paul",
    ("maplewood",            "MN"): "Minneapolis-St. Paul",
    ("roseville",            "MN"): "Minneapolis-St. Paul",
    ("shoreview",            "MN"): "Minneapolis-St. Paul",
    ("fridley",              "MN"): "Minneapolis-St. Paul",
    ("columbia heights",     "MN"): "Minneapolis-St. Paul",
    ("blaine",               "MN"): "Minneapolis-St. Paul",
    ("inver grove heights",  "MN"): "Minneapolis-St. Paul",
    ("chaska",               "MN"): "Minneapolis-St. Paul",
    ("chanhassen",           "MN"): "Minneapolis-St. Paul",
    ("shakopee",             "MN"): "Minneapolis-St. Paul",
    ("prior lake",           "MN"): "Minneapolis-St. Paul",
    ("savage",               "MN"): "Minneapolis-St. Paul",
    # ── Ohio ────────────────────────────────────────────────────────────────────
    ("columbus",             "OH"): "Columbus",
    ("dublin",               "OH"): "Columbus",
    ("westerville",          "OH"): "Columbus",
    ("grove city",           "OH"): "Columbus",
    ("hilliard",             "OH"): "Columbus",
    ("reynoldsburg",         "OH"): "Columbus",
    ("gahanna",              "OH"): "Columbus",
    ("lewis center",         "OH"): "Columbus",
    ("new albany",           "OH"): "Columbus",
    ("canal winchester",     "OH"): "Columbus",
    ("cleveland",            "OH"): "Cleveland",
    ("akron",                "OH"): "Cleveland",
    ("parma",                "OH"): "Cleveland",
    ("lorain",               "OH"): "Cleveland",
    ("strongsville",         "OH"): "Cleveland",
    ("lakewood",             "OH"): "Cleveland",
    ("euclid",               "OH"): "Cleveland",
    ("mentor",               "OH"): "Cleveland",
    ("medina",               "OH"): "Cleveland",
    ("elyria",               "OH"): "Cleveland",
    ("north olmsted",        "OH"): "Cleveland",
    ("beachwood",            "OH"): "Cleveland",
    ("cleveland heights",    "OH"): "Cleveland",
    ("solon",                "OH"): "Cleveland",
    ("westlake",             "OH"): "Cleveland",
    ("brunswick",            "OH"): "Cleveland",
    ("cincinnati",           "OH"): "Cincinnati",
    ("hamilton",             "OH"): "Cincinnati",
    ("fairfield",            "OH"): "Cincinnati",
    ("mason",                "OH"): "Cincinnati",
    ("blue ash",             "OH"): "Cincinnati",
    ("westchester",          "OH"): "Cincinnati",
    ("anderson township",    "OH"): "Cincinnati",
    ("covington",            "KY"): "Cincinnati",
    ("florence",             "KY"): "Cincinnati",
    ("dayton",               "OH"): "Dayton",
    ("kettering",            "OH"): "Dayton",
    ("toledo",               "OH"): "Toledo",
    # ── Michigan ────────────────────────────────────────────────────────────────
    ("detroit",              "MI"): "Detroit",
    ("warren",               "MI"): "Detroit",
    ("sterling heights",     "MI"): "Detroit",
    ("ann arbor",            "MI"): "Detroit",
    ("livonia",              "MI"): "Detroit",
    ("dearborn",             "MI"): "Detroit",
    ("westland",             "MI"): "Detroit",
    ("troy",                 "MI"): "Detroit",
    ("farmington hills",     "MI"): "Detroit",
    ("southfield",           "MI"): "Detroit",
    ("clinton township",     "MI"): "Detroit",
    ("canton",               "MI"): "Detroit",
    ("shelby township",      "MI"): "Detroit",
    ("rochester hills",      "MI"): "Detroit",
    ("pontiac",              "MI"): "Detroit",
    ("auburn hills",         "MI"): "Detroit",
    ("royal oak",            "MI"): "Detroit",
    ("novi",                 "MI"): "Detroit",
    ("grand rapids",         "MI"): "Grand Rapids",
    ("wyoming",              "MI"): "Grand Rapids",
    ("kentwood",             "MI"): "Grand Rapids",
    ("comstock park",        "MI"): "Grand Rapids",
    ("walker",               "MI"): "Grand Rapids",
    ("lansing",              "MI"): "Lansing",
    # ── Indiana ─────────────────────────────────────────────────────────────────
    ("indianapolis",         "IN"): "Indianapolis",
    ("carmel",               "IN"): "Indianapolis",
    ("fishers",              "IN"): "Indianapolis",
    ("noblesville",          "IN"): "Indianapolis",
    ("greenwood",            "IN"): "Indianapolis",
    ("lawrence",             "IN"): "Indianapolis",
    ("avon",                 "IN"): "Indianapolis",
    ("plainfield",           "IN"): "Indianapolis",
    ("zionsville",           "IN"): "Indianapolis",
    ("fort wayne",           "IN"): "Ft. Wayne",
    # ── Missouri / Kansas ────────────────────────────────────────────────────────
    ("kansas city",          "MO"): "Kansas City",
    ("independence",         "MO"): "Kansas City",
    ("st. joseph",           "MO"): "Kansas City",
    ("lees summit",          "MO"): "Kansas City",
    ("overland park",        "KS"): "Kansas City",
    ("olathe",               "KS"): "Kansas City",
    ("shawnee",              "KS"): "Kansas City",
    ("kansas city",          "KS"): "Kansas City",
    ("lenexa",               "KS"): "Kansas City",
    ("leawood",              "KS"): "Kansas City",
    ("st. louis",            "MO"): "St. Louis",
    ("saint louis",          "MO"): "St. Louis",
    ("florissant",           "MO"): "St. Louis",
    ("chesterfield",         "MO"): "St. Louis",
    ("ballwin",              "MO"): "St. Louis",
    ("o fallon",             "MO"): "St. Louis",
    ("st. charles",          "MO"): "St. Louis",
    ("st. peters",           "MO"): "St. Louis",
    ("belleville",           "IL"): "St. Louis",
    ("edwardsville",         "IL"): "St. Louis",
    # ── Wisconsin ───────────────────────────────────────────────────────────────
    ("milwaukee",            "WI"): "Milwaukee",
    ("waukesha",             "WI"): "Milwaukee",
    ("racine",               "WI"): "Milwaukee",
    ("kenosha",              "WI"): "Milwaukee",
    ("west allis",           "WI"): "Milwaukee",
    ("wauwatosa",            "WI"): "Milwaukee",
    ("greenfield",           "WI"): "Milwaukee",
    ("madison",              "WI"): "Madison",
    ("fitchburg",            "WI"): "Madison",
    ("sun prairie",          "WI"): "Madison",
    # ── Kentucky ────────────────────────────────────────────────────────────────
    ("louisville",           "KY"): "Louisville",
    ("lexington",            "KY"): "Lexington",
    # ── Alabama ─────────────────────────────────────────────────────────────────
    ("birmingham",           "AL"): "Birmingham",
    ("hoover",               "AL"): "Birmingham",
    ("huntsville",           "AL"): "Huntsville",
    ("madison",              "AL"): "Huntsville",
    ("montgomery",           "AL"): "Montgomery",
    ("mobile",               "AL"): "Mobile",
    # ── Oklahoma ────────────────────────────────────────────────────────────────
    ("oklahoma city",        "OK"): "Oklahoma City",
    ("norman",               "OK"): "Oklahoma City",
    ("edmond",               "OK"): "Oklahoma City",
    ("moore",                "OK"): "Oklahoma City",
    ("midwest city",         "OK"): "Oklahoma City",
    ("tulsa",                "OK"): "Tulsa",
    ("broken arrow",         "OK"): "Tulsa",
    ("owasso",               "OK"): "Tulsa",
    # ── Louisiana ───────────────────────────────────────────────────────────────
    ("new orleans",          "LA"): "New Orleans",
    ("metairie",             "LA"): "New Orleans",
    ("kenner",               "LA"): "New Orleans",
    ("baton rouge",          "LA"): "Baton Rouge",
    ("prairieville",         "LA"): "Baton Rouge",
    ("shreveport",           "LA"): "Shreveport",
    # ── New Mexico ──────────────────────────────────────────────────────────────
    ("albuquerque",          "NM"): "Albuquerque",
    ("rio rancho",           "NM"): "Albuquerque",
    ("santa fe",             "NM"): "Santa Fe",
    # ── Idaho ───────────────────────────────────────────────────────────────────
    ("boise",                "ID"): "Boise City",
    ("nampa",                "ID"): "Boise City",
    ("meridian",             "ID"): "Boise City",
    ("caldwell",             "ID"): "Boise City",
    ("eagle",                "ID"): "Boise City",
    ("garden city",          "ID"): "Boise City",
    ("twin falls",           "ID"): "Twin Falls",
    # ── Montana / Wyoming ────────────────────────────────────────────────────────
    ("billings",             "MT"): "Billings",
    ("missoula",             "MT"): "Missoula",
    ("cheyenne",             "WY"): "Cheyenne",
    # ── Hawaii ──────────────────────────────────────────────────────────────────
    ("honolulu",             "HI"): "Honolulu",
    ("pearl city",           "HI"): "Honolulu",
    ("ewa beach",            "HI"): "Honolulu",
    ("kapolei",              "HI"): "Honolulu",
    ("kailua",               "HI"): "Honolulu",
    ("kaneohe",              "HI"): "Honolulu",
    # ── Midwest misc ────────────────────────────────────────────────────────────
    ("omaha",                "NE"): "Omaha",
    ("lincoln",              "NE"): "Omaha",
    ("des moines",           "IA"): "Des Moines",
    ("sioux falls",          "SD"): "Sioux Falls",
    ("fargo",                "ND"): "Fargo",
    ("wichita",              "KS"): "Wichita",
}


MSA_OPTIONS: list[str] = sorted({
    "Albany", "Albuquerque", "Altoona", "Anaheim-Santa Ana-Irvine",
    "Asheville", "Atlanta", "Augusta", "Austin",
    "Bakersfield", "Baltimore", "Billings", "Birmingham", "Boise City",
    "Boston", "Boulder", "Bridgeport-Stamford", "Buffalo-Cheektowaga",
    "Cape Coral-Ft. Myers", "Charleston", "Charlotte", "Chattanooga",
    "Cheyenne", "Chicago", "Cincinnati", "Clarksville",
    "Cleveland", "Colorado Springs", "Columbia", "Columbus",
    "Columbus-Phenix City", "Corvallis", "Dallas-Plano-Irving", "Dayton",
    "Denver", "Des Moines", "Detroit", "Eugene", "El Paso",
    "Fargo", "Fresno", "Ft. Collins", "Ft. Lauderdale-Pompano",
    "Ft. Wayne", "Ft. Worth-Arlington", "Gainesville", "Grand Rapids",
    "Greeley", "Greensboro", "Greenville", "Harrisburg", "Hartford",
    "Honolulu", "Houston", "Huntsville", "Indianapolis",
    "Jacksonville", "Kansas City", "Knoxville",
    "L.A. - Long Beach-Glendale", "Lakeland-Winter Haven", "Lansing",
    "Las Vegas", "Lexington", "Louisville",
    "Madison", "McAllen", "Memphis", "Miami-Kendall",
    "Milwaukee", "Minneapolis-St. Paul", "Missoula", "Mobile",
    "Modesto", "Montgomery", "Myrtle Beach",
    "N. Port-Sarasota-Bradenton", "Naples-Marco Island",
    "Nashville", "Nassau Co. - Suffolk Co.", "New Haven",
    "New Orleans", "New York-White Plains", "Newark-Jersey City",
    "Norfolk-Virginia Beach", "Oakland-Hayward-Berkeley",
    "Ogden-Clearfield", "Oklahoma City", "Olympia-Lacey-Tumwater",
    "Omaha", "Orlando", "Oxnard-Thousand Oaks",
    "Palm Bay-Melbourne", "Pensacola", "Philadelphia",
    "Phoenix", "Pittsburgh", "Portfolio", "Portland", "Provo-Orem",
    "Raleigh", "Reno", "Richmond", "Riverside-San Bernardino",
    "Rochester", "Sacramento", "Salem", "Salt Lake City",
    "San Antonio", "San Diego", "San Francisco",
    "San Jose-Sunnyvale-S. Clara", "Santa Fe",
    "Santa Maria-Santa Barbara", "Santa Rosa", "Savannah",
    "Seattle", "Shreveport", "Sioux Falls", "Spokane",
    "Springfield", "St. Louis", "Stockton",
    "Syracuse", "Tacoma-Lakewood", "Tallahassee",
    "Tampa-St. Pete", "Toledo", "Tucson", "Tulsa",
    "Twin Falls", "Vallejo/Fairfield/Napa", "Visalia-Porterville",
    "Washington-Northern VA", "West Palm-Boca-Delray",
    "Wichita", "Wilmington", "Winston-Salem", "Worcester",
})


COUNTY_OPTIONS: list[str] = sorted({
    "Alameda", "Allegheny", "Arapahoe", "Arlington", "Alachua",
    "Baltimore City", "Baltimore County", "Bergen", "Bernalillo",
    "Boulder", "Brevard", "Broward", "Bucks",
    "Charleston", "Chester", "Clark", "Cobb", "Collin", "Columbus",
    "Cook", "Contra Costa", "Coweta",
    "Dallas", "Davidson", "DeKalb", "Denver", "Denton", "Douglas",
    "DuPage", "Durham",
    "El Paso", "Essex",
    "Fairfax", "Fayette", "Forsyth", "Franklin", "Fresno", "Fulton",
    "Gwinnett",
    "Hamilton", "Harris", "Hennepin", "Hillsborough",
    "Iredell", "Jefferson",
    "Kane", "King", "Kings", "Knox",
    "Lake", "Los Angeles", "Loudoun",
    "Manatee", "Maricopa", "Mecklenburg", "Miami-Dade", "Middlesex",
    "Milwaukee", "Multnomah",
    "New Castle", "Norfolk City",
    "Orange", "Osceola",
    "Palm Beach", "Pierce", "Pinellas", "Polk", "Portfolio",
    "Prince George's", "Prince William",
    "Queens",
    "Ramsey", "Richmond County", "Riverside",
    "Sacramento", "San Bernardino", "San Diego", "San Mateo",
    "Santa Clara", "Sarasota", "Seminole", "Shelby", "Snohomish",
    "Suffolk", "Summit",
    "Tarrant", "Travis",
    "Utah County",
    "Ventura",
    "Wake", "Washoe", "Wayne", "Williamson",
    "Yolo",
})


STATE_OPTIONS: list[str] = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL",
    "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
    "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
    "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
]


SUBMARKET_OPTIONS: list[str] = sorted({
    # Atlanta
    "Alpharetta/Cumming", "Buckhead", "Decatur/Tucker",
    "Downtown Atlanta", "Duluth/Lawrenceville", "East Atlanta/Kirkwood",
    "Kennesaw/Acworth", "Marietta/Smyrna", "Midtown Atlanta",
    "Norcross/Peachtree Corners", "Peachtree City/Fayetteville",
    "Sandy Springs/Roswell", "Stockbridge/McDonough",
    # Austin
    "Cedar Park/Leander", "Downtown Austin", "East Austin",
    "Georgetown/Round Rock", "Kyle/Buda", "Mueller/Windsor Park",
    "North Austin", "Northwest Austin/Arboretum", "South Austin",
    "Southwest Austin", "The Domain", "West Austin/Rollingwood",
    # Baltimore
    "Annapolis", "Baltimore City East", "Baltimore City North",
    "Baltimore City West", "Columbia/Ellicott City",
    "Downtown Baltimore", "Harbor East", "Inner Harbor",
    "Towson/Timonium",
    # Boston
    "Allston/Brighton", "Back Bay", "Cambridge/Somerville",
    "Charlestown", "Dorchester", "East Boston", "Fenway/Kenmore",
    "Jamaica Plain", "Lexington/Concord", "Lowell/Lawrence",
    "Lynn/Peabody", "Midtown Boston", "Natick/Framingham",
    "Newton/Brookline", "North End/Waterfront", "North Shore",
    "Quincy/Braintree", "Seaport/South Boston",
    "South End", "Waltham/Watertown", "West Roxbury/Roslindale",
    "West Cambridge / Alewife", "Woburn/Burlington",
    # Charlotte
    "Ballantyne", "Concord/Kannapolis", "Davidson/Cornelius",
    "Downtown Charlotte", "Gastonia/Belmont", "Huntersville",
    "Indian Trail/Matthews", "Midtown Charlotte", "Mooresville",
    "South Charlotte", "South End/Dilworth", "University/NE Charlotte",
    # Chicago
    "Arlington Heights/Palatine/Wheeling", "Aurora/Naperville",
    "Bronzeville/Hyde Park/South Shore", "Bucktown/Wicker Park",
    "Downtown Chicago (Loop)", "Evanston/Skokie", "Gold Coast",
    "Joliet/Lockport", "Lake County", "Lincoln Park/Old Town",
    "Lakeview/Uptown", "Near North Side", "Orland Park/Tinley Park",
    "Pilsen/Little Village", "Rogers Park/Edgewater",
    "Schaumburg/Elk Grove", "South Loop/Bronzeville",
    "Streeterville/River North", "Waukegan/North Chicago",
    "West Loop/Fulton Market", "West Suburbs",
    # Dallas-Fort Worth
    "Addison/Bent Tree", "Allen/McKinney", "Arlington/Grand Prairie",
    "Carrollton/Farmers Branch", "Denton", "Far North Dallas",
    "Fort Worth Central", "Frisco/Prosper", "Garland/Mesquite",
    "Grapevine/Southlake/Colleyville", "Keller/N. Richland Hills",
    "Las Colinas/Irving", "Lewisville/Flower Mound",
    "Mansfield/Burleson", "Plano/Richardson",
    "Preston Hollow/Vickery Meadow", "Rockwall/Forney",
    "Uptown Dallas", "West Fort Worth",
    # Denver
    "Arvada/Golden", "Aurora Central", "Aurora South/Centennial",
    "Boulder", "Broomfield", "Capitol Hill/Cherry Creek",
    "Castle Rock/Parker", "Colorado Springs", "Commerce City",
    "Downtown Denver", "Englewood/Littleton", "Highlands Ranch",
    "LoDo/Union Station", "Lone Tree/Highlands Ranch South",
    "Northglenn/Thornton", "Westminster",
    # Houston
    "Baytown", "Brazoria County", "Clear Lake/Webster",
    "Cypress", "Energy Corridor", "Fort Bend/Sugar Land",
    "Galleria/Uptown", "Heights/Montrose/Midtown",
    "Humble/Atascocita", "Inner Loop East",
    "Katy", "Kingwood/Humble", "League City/Friendswood",
    "Medical Center/Greenway Plaza", "Memorial/Spring Branch",
    "Midtown Houston", "Pearland", "The Woodlands/Conroe",
    # Los Angeles
    "Antelope Valley", "Beverly Hills/West Hollywood",
    "Brentwood/Westwood/Beverly Hills", "Burbank/Glendale/Pasadena",
    "Carson/Torrance/Gardena", "Century City/Westwood",
    "Chatsworth/Northridge", "Covina/West Covina",
    "Culver City/Marina del Rey", "Downtown LA",
    "El Monte/San Gabriel Valley East", "Hollywood/Los Feliz",
    "Inglewood/Hawthorne", "Koreatown/Pico Union",
    "Long Beach", "Mid-City/Mid-Wilshire",
    "North Hollywood/Studio City", "Norwalk/Downey",
    "Pomona/Diamond Bar", "Santa Clarita/Valencia",
    "Santa Monica/Brentwood", "Sherman Oaks/Encino",
    "Silver Lake/Echo Park", "South Bay", "Sylmar/Granada Hills",
    "Venice/Marina del Rey", "West Adams", "Woodland Hills/Tarzana",
    # Miami-Fort Lauderdale
    "Aventura/Hallandale", "Boca Raton",
    "Boynton Beach/Delray Beach", "Coconut Grove/Coral Gables",
    "Coral Springs/Margate", "Deerfield Beach/Pompano Beach",
    "Doral/Airport", "Downtown Fort Lauderdale",
    "Downtown Miami", "Edgewater/Wynwood",
    "Hollywood/Davie", "Kendall", "Little Haiti/Little Havana",
    "Miramar/Pembroke Pines", "North Miami Beach",
    "North Miami/Aventura", "Plantation/Sunrise",
    "South Beach", "West Palm Beach/Wellington",
    # Minneapolis
    "Anoka County", "Bloomington", "Brooklyn Park",
    "Burnsville/Apple Valley", "Coon Rapids/Blaine",
    "Downtown Minneapolis", "Downtown St. Paul",
    "Eagan/Apple Valley", "Eden Prairie/Minnetonka",
    "Edina/Richfield", "Lakeville/Savage",
    "Maple Grove/Plymouth", "Shakopee/Prior Lake",
    "Woodbury/Lake Elmo",
    # Nashville
    "Antioch/Brentwood South", "Berry Hill/Melrose",
    "Downtown Nashville", "East Nashville", "Franklin",
    "Gallatin/Hendersonville", "Germantown/Salemtown",
    "Green Hills/Belle Meade", "Lebanon/Mt. Juliet",
    "Murfreesboro", "North Nashville", "Smyrna/La Vergne",
    "Spring Hill/Columbia", "West Nashville/Belle Meade",
    # New York
    "Bergen County", "Bronx", "Brooklyn", "Downtown Manhattan",
    "Essex County", "Hudson Heights/Inwood", "Midtown Manhattan",
    "Nassau Co. - Suffolk Co.", "Northern NJ",
    "Queens", "Staten Island", "Upper East Side",
    "Upper West Side", "Westchester County",
    # Orange County (CA)
    "Anaheim/Orange", "Buena Park/Cypress", "Costa Mesa/Newport Beach",
    "Fullerton/Placentia", "Irvine/Tustin", "Laguna Hills/Mission Viejo",
    "North Orange County", "Santa Ana",
    # Orlando
    "Altamonte Springs/Apopka", "Downtown Orlando", "East Orlando",
    "Kissimmee/Osceola", "Lake Mary/Sanford", "North Orlando",
    "Ocoee/Winter Garden", "South Orlando", "Winter Park",
    # Philadelphia
    "Bucks County", "Burlington County", "Camden/Gloucester County",
    "Center City Philadelphia", "Chester County",
    "Delaware County", "Main Line", "Montgomery County",
    "North Philadelphia", "Northeast Philadelphia", "South Philadelphia",
    # Phoenix
    "Ahwatukee/South Mountain", "Avondale/Goodyear/West Glendale",
    "Buckeye/Tolleson", "Chandler/Gilbert",
    "Downtown Phoenix", "Gilbert/Queen Creek",
    "Glendale/Peoria", "Mesa Central", "Mesa East",
    "Phoenix North/Desert Ridge", "Scottsdale Central",
    "Scottsdale North", "Scottsdale South/Tempe",
    "Surprise/El Mirage", "Tempe/University",
    # Portland
    "Aloha/West Beaverton", "Beaverton/Hillsboro",
    "Downtown Portland", "East Portland/Gresham",
    "Happy Valley/Oregon City", "Lake Oswego/Tualatin",
    "North Portland", "Northeast Portland", "Northwest Portland",
    "Pearl District", "Southeast Portland",
    "Tigard/Sherwood/Wilsonville", "Vancouver/Camas",
    # Raleigh-Durham
    "Apex/Holly Springs", "Cary", "Chapel Hill", "Downtown Durham",
    "Downtown Raleigh", "Durham/Research Triangle Park",
    "Fuquay Varina", "Garner/Clayton", "Morrisville",
    "North Raleigh", "Research Triangle Park",
    "South Durham", "Wake Forest/Rolesville",
    # Sacramento
    "Downtown Sacramento", "Elk Grove", "Folsom/El Dorado Hills",
    "Natomas", "North Natomas", "Rancho Cordova",
    "Roseville/Rocklin", "West Sacramento",
    # San Diego
    "Chula Vista/National City", "Downtown San Diego/Little Italy",
    "Eastlake/Otay Ranch", "El Cajon/Santee",
    "Escondido/San Marcos", "Hillcrest/Mission Hills",
    "La Jolla/UTC", "Mission Valley/Kearny Mesa",
    "North County Coastal", "North County Inland",
    "Ocean Beach/Point Loma", "Oceanside/Carlsbad",
    "Pacific Beach/Bay Park", "Poway", "South Bay",
    # San Francisco Bay Area
    "Burlingame/San Mateo", "Daly City/Colma",
    "Downtown San Francisco", "Foster City/Redwood City",
    "Fremont/Newark", "Menlo Park/Palo Alto",
    "Mission/SoMa", "Nob Hill/Russian Hill",
    "Potrero Hill/Bernal Heights", "Richmond District",
    "Sunset District",
    # Seattle
    "Ballard/Crown Hill", "Bear Creek",
    "Bellevue/Mercer Island", "Bothell/Kenmore",
    "Capitol Hill/First Hill", "Downtown Seattle",
    "Eastside/Redmond", "Edmonds/Lynnwood",
    "Everett/Marysville", "Federal Way/Auburn",
    "Issaquah/Sammamish", "Kirkland/Juanita",
    "Kent/Renton", "Northgate/Lake City",
    "Queen Anne/Magnolia", "Shoreline",
    "South Seattle", "University District",
    # Tampa
    "Brandon/Southeast Hillsborough County",
    "Clearwater/Safety Harbor", "Downtown St. Petersburg",
    "Downtown Tampa", "Dunedin/Palm Harbor",
    "Land O Lakes/Wesley Chapel", "Largo/Pinellas Park",
    "New Port Richey/Port Richey", "Riverview/Apollo Beach",
    "South Tampa/Hyde Park", "Seminole/Madeira Beach",
    "Temple Terrace/New Tampa",
    # Washington DC
    "Annandale/Springfield", "Annapolis", "Arlington", "Ashburn/Sterling",
    "Bethesda/Chevy Chase", "Capitol Hill/Navy Yard",
    "Centreville/Chantilly", "College Park/Prince George's County",
    "Downtown DC/Penn Quarter", "Dupont Circle/Logan Circle",
    "Falls Church/Merrifield", "Fairfax/Vienna",
    "Germantown/Gaithersburg", "Leesburg/Loudoun County",
    "McLean/Tysons", "Manassas/Prince William",
    "Reston/Herndon", "Rockville/North Bethesda",
    "Silver Spring/Takoma Park", "Waldorf/Charles County",
    "Woodbridge/Dale City",
    # Misc
    "Airport Area", "Anderson", "Arboretum", "Baymeadows",
    "Briarcliff", "Campus Area", "Central Business District",
    "Downtown", "Medical District", "Midtown",
    "Old Town", "Suburban", "University Area",
})


TYPE_OPTIONS: list[str] = [
    "Garden / tbd", "Garden / Wood", "Garden / Concrete", "Garden / Steel",
    "Garden HD / tbd", "Garden HD / Wood", "Garden HD / Concrete", "Garden HD / Steel",
    "Mid-Rise Wrap / tbd", "Mid-Rise Wrap / Wood", "Mid-Rise Wrap / Concrete", "Mid-Rise Wrap / Steel",
    "Mid-Rise Podium / tbd", "Mid-Rise Podium / Wood", "Mid-Rise Podium / Concrete", "Mid-Rise Podium / Steel",
    "High-Rise / tbd", "High-Rise / Wood", "High-Rise / Concrete", "High-Rise / Steel",
    "Other",
]

BROKERAGE_OPTIONS: list[str] = [
    "Berkadia", "C&W", "CBRE", "Eastdil", "Engler", "IPA", "JLL",
    "Kidder Mathews", "Newmark", "Northmarq", "W&D", "W&D / Engler",
    "BlueGate", "Patterson", "Colliers", "Bravo & Partners",
    "HFF", "Marcus & Millichap", "Avison Young", "Transwestern",
    "Walker & Dunlop", "Greystone", "Ariel Property Advisors",
    "RealSource", "Institutional Property Advisors", "SRS Real Estate",
    "none",
]


def msa_for_deal(deal: dict) -> str:
    """Return the MSA label for a deal dict, falling back to raw city name."""
    cs = deal.get("city_state", "")
    parts = cs.split(",")
    city  = parts[0].strip().lower()
    state = parts[1].strip().upper() if len(parts) > 1 else ""
    return _CITY_TO_MSA.get((city, state)) or cs.split(",")[0].strip().title() or "Other"
